language: rust
dist: bionic
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo test'
  - 'cargo test -p test_2015 -p test_2018'
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --release --all-targets; fi'
  - 'if [ "$TRAVIS_RUST_VERSION" != "1.31.0"  ]; then cargo test -p test_compile_errors; fi'

# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: # important!
matrix:
  include:
    - rust: 1.31.0
    - rust: 1.31.0
      env: WITH_LOCK=true
    - rust: stable
      env: WITH_LOCK=true
    - rust: nightly
      env: MAY_FAIL=true
    - rust: 1.31.0
      os: osx
      env: WITH_LOCK=true
  allow_failures:
    - env: MAY_FAIL=true
