[package]
name          = "test_2015"
version       = "6.6.6"
publish       = false
edition       = "2015"

[dependencies]
tao-log = { version=">= 0.1.0, <= 9000.0.0", path = ".." }

[lib]
doctest = false
test = true
